### ISSUE TITLE
Sans incorrectly logs discard as your own

### ISSUE THREAD

**Issue by feildmaster** [feildmaster/UnderScript#1]
When playing sans, the discard log says you discarded, rather than the opponent.

**Comment by nwawrzyniak** [comment]
I guess this could be closed because there is no single "discard" effect left in the current patch? The closest things would be things like Trash Tornado or Memory Head that shuffle cards back into the opponents deck.

**Comment by feildmaster** [comment]
Manticore can still trigger this if your opponent has full hand.

Not sure what else can do it. Although I should check to see if Onu applied the fix I asked him for sometime (which would close this ticket anyway)

**Comment by feildmaster** [comment]
In fact this has indeed been fixed
![](https://i.imgur.com/iJr4kku.png)
