### ISSUE TITLE
some functions of the underscript do not work for me

### ISSUE THREAD

**Issue by Lomba10** [feildmaster/UnderScript#26]
I have had a problem with the underscript in which the dust counter or deck storage does not work. Some features of the underscript work and others do not :c

**Comment by feildmaster** [comment]
Version of UnderScript? If it's not 0.20.7 update it.

**Comment by feildmaster** [comment]
Or rather, wow. This is an old thread. Uhmm... Yes, it's fixed by now, thanks for the report!
